version: "3"

services:

  db:
    image: registry.hub.docker.com/juanforo/dvwa-db
    restart: always
    ports:
      - "3306:3306"

  app:
    image: registry.hub.docker.com/juanforo/dvwa-test
    restart: always
    ports:
      - "5000:80"
    links:
      - db
